### ISSUE TITLE
Minor inconsistencies for palmerpenguins vs. viridis

### ISSUE THREAD

**Issue by spcanelon** [mine-cetinkaya-rundel/improve-repro-workflow-reproducibilitea-2020#1]
Hello @mine-cetinkaya-rundel 👋 

Thank you for sharing this reproducibility workflow resource -- I found it really helpful and the slide deck is lovely! 😃 

I wanted to give you a heads up that slides 10 and 29 each have old references to the `viridis` dataset instead of `palmerpenguins`

Slide 10 has one in the Table 1 caption:
![image](https://user-images.githubusercontent.com/49913337/103031509-f7e7b580-452b-11eb-9659-675e541b8f75.png)

Slide 29 has one in the figure:
![image](https://user-images.githubusercontent.com/49913337/103031572-1948a180-452c-11eb-9ca0-68e69a375a85.png)

**Comment by mine-cetinkaya-rundel** [comment]
Thanks @spcanelon, fixed now!
